MAC = "BE:89:80:02:EE:EF"

modes = {
    'red': '80',
    'blue': '81',
    'green': '82',
    'cyan': '83',
    'yellow': '84',
    'magenta': '85',
    'white': '86', 
    'jump rgb': '87',
    'jump rgbycmw': '88',
    'gradient rgb': '89',
    'gradient rgbycmw': '8a',
    'gradient r': '8b',
    'gradient g': '8c',
    'gradient b': '8d',
    'gradient y': '8e',
    'gradient c': '8f',
    'gradient m': '90',
    'gradient w': '91',
    'gradient rg': '92',
    'gradient rb': '93', 
    'gradient gb': '94',
    'blink rgbycmw': '95',
    'blink r': '96',
    'blink g': '97',
    'blink b': '98',
    'blink y': '99',
    'blink c': '9a',
    'blink m': '9b',
    'blink w': '9c'
    }